services:
  # PostgreSQL with pgvector
  postgres:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_DB: storydb
      POSTGRES_USER: storyuser
      POSTGRES_PASSWORD: storypass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./simple_schema.sql:/docker-entrypoint-initdb.d/init.sql

  # FastAPI Memory Service
  memory-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://storyuser:storypass@postgres/storydb
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      - postgres
    volumes:
      - .:/app

volumes:
  postgres_data: